image: bradrydzewski/python:3.3
script:
 - pip install tox -f wheelhouse
 - tox
 - echo {{notify_url}}
notify:
 webhook:
  urls:
   - {{notify_url}}
  on_started: true
  on_success: true
  on_failure: true
